### ISSUE TITLE
Desktop can't be selected as output folder

### ISSUE THREAD

**Issue by nineff** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#34] opened 2021-04-07 14:18 UTC
Version 2.0 Release, Win 10 x64
Choosing the Desktop as output directory fails with the error message "Kein Object für Moniker" (No Object for Moniker)
This might as well be an Inkscape or GTK Bug, but I've only noticed it here.
Creating a new folder below the desktop and choosing that works, though.

**Comment by PadLex** [comment] 2021-04-07 22:10
I think you're right, this does look like an Inscape bug.  However I can't reproduce it. Perhaps it has to do with your unique path structure?

**Comment by nineff** [comment] 2021-04-09 13:58
my path structure is very ordinary, in my case it is `C:\Users\Niko\Desktop`. But perhaps it only appears for localized Windows versions, since I'm using the German one?

**Comment by PadLex** [comment] 2021-04-11 10:01
Well that's odd. You might want to write a bug report on [Inkscape's official repo](https://gitlab.com/inkscape/inkscape/-/issues). Since it doesn't look like this extension caused the bug, I'll close this issue.

**Closed by PadLex** 2021-04-11 10:01 UTC
Labels: bug, workaround
